name: Cypress run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - run: npm ci
    - run: npm run build

    - name: Run Keycloak
      run: ./start.js & sleep 40

    - name: Run Admin Console
      run: npx http-server ./build/src/main/resources/admin/resources -P http://localhost:8180/ & sleep 30

    - name: Admin Console client
      run: ./import.js

    - name: Cypress run
      run: npm run start:cypress-tests

    - name: Add Cypress videos artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-videos
        path: assets/videos

    - name: Add Cypress screenshots artifacts
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: assets/screenshots